version: "3.7"
services:
        bancogeral:
                image: mysql:5.7
                container_name: bancogeral
                environment:
                        MYSQL_ROOT_PASSWORD: root
                ports:
                        - "3306:3306"
                volumes:
                        - ./SQL/:/var/lib/mysql
        phpmyadmin:
                image: phpmyadmin/phpmyadmin:latest
                depends_on:
                        - bancogeral
                links:
                        - bancogeral:bancogeral
                ports:
                        - "443:80"
                environment:
                        - PMA_ARBITRARY=1
        registrovisitas:
                depends_on:
                        - bancogeral
                links:
                        - bancogeral:bancogeral
                build: 
                        context: .
                        dockerfile: ./Docker_files/Dockerfile.registrovisitas
                container_name: registrovisitas
                ports:
                        - "80:80"
        registrofuncionarios:
                depends_on:
                        - bancogeral
                links:
                        - bancogeral:bancogeral
                build: 
                        context: .
                        dockerfile: ./Docker_files/Dockerfile.registrofuncionarios
                container_name: registrofuncionarios
                ports:
                        - "81:80"
        registrocaminhoes:
                depends_on:
                        - bancogeral
                links:
                        - bancogeral:bancogeral
                build: 
                        context: .
                        dockerfile: ./Docker_files/Dockerfile.registrocaminhoes
                container_name: registrocaminhoes
                ports:
                        - "82:80"
