version: "3.7"
services:
        bancogeral:
                image: mysql:5.7
                container_name: bancogeral
                environment:
                        MYSQL_ROOT_PASSWORD: root
                ports:
                        - "3306:3306"
        phpmyadmin:
                image: phpmyadmin/phpmyadmin:latest
                depends_on:
                        - bancogeral
                links:
                        - bancogeral:bancogeral
                ports:
                        - "443:80"
                environment:
                        - PMA_ARBITRARY=1
        registrosvisitas:
                depends_on:
                        - bancogeral
                links:
                        - bancogeral:bancogeral
                build: 
                        context: .
                        dockerfile: Dockerfile 
                container_name: registrovisitas
                ports:
                        - "80:80"
                volumes:
                        - ./registrovisitas/:/var/www/html
        registrosfuncionarios:
                depends_on:
                        - bancogeral
                links:
                        - bancogeral:bancogeral
                build: 
                        context: .
                        dockerfile: Dockerfile 
                container_name: registrofuncionarios
                ports:
                        - "81:80"
                volumes:
                        - ./registrofuncionarios/:/var/www/html
        registrosfotos:
                depends_on:
                        - bancogeral
                links:
                        - bancogeral:bancogeral
                build: 
                        context: .
                        dockerfile: Dockerfile 
                container_name: registrofotos
                ports:
                        - "82:80"
                volumes:
                        - ./registrofotos/:/var/www/html

