FROM php:7.2-apache
RUN docker-php-ext-install mysqli 
RUN apt update && apt install git -y 
RUN git clone https://github.com/guilhermeG23/registros_portaria_web_simples && rm -rf /var/www/html/index.html && mv registros_portaria_web_simples/* /var/www/html/ && rm -rf registros_portaria_web_simples
